### ISSUE TITLE
prepare for going public

### ISSUE THREAD

**Issue by aldy505** [teknologi-umum/bot#44]
karena bot ini OSS, agak serakah menurutku kalau we keep it to Teknologi Umum. udah lama kepikiran biar bot ini bisa dipake di grup lain.

tapi tentu saja, harus ada beberapa hal yang di adjust biar bot ini masih aman:
- [x] safe word list filter on `/search` command (#57 #55 #54 #52 #51)
- [x] disable `/joke`, `/illuminati`, `/ynkts`, `/kktybs` , `/quote` kalo member grup nya diatas 500 orang (#46)
- [x] set command `/quiz`, `/blidingej` exclusive ke grup teknologi umum (#46)
- [x] delete `/time` command (#46)
- [x] benerin konten dari `/help` biar lebih helpful (#61)
- [x] pin poll cuma bisa di grup teknologi umum (#46)
- [x] bikin documentation tentang cara tambahiin bot ke grup dan cara pake bot nya di repository ini (#53)
- [x] ~~`/kick` and `/ban` command, along with `/enable` and `/disable` command (see #56)~~
- [ ] implement statistics, jadi bisa tau bot ini ada di server mana aja (#70)

project issue ini lumayan jangka panjang, jangan di buru-buruin. kita semua punya kehidupan. mungkin kamu punya teman 2D yang harus diajak ngobrol.
